#!/usr/bin/env bash
# Configures an Ubuntu server: localhost resolves to 127.0.0.2 and facebook.com to 8.8.8.8
sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/' /etc/hosts
if ! grep -q 'facebook.com' /etc/hosts; then
    echo '8.8.8.8 facebook.com' >> /etc/hosts
else
    sed -i 's/.*facebook.com.*/8.8.8.8 facebook.com/' /etc/hosts
fi
